# Copyright (C) 2020-2021 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Director's config.
# Parameters:
#   1. sample_shape - sample shape interface unified across the Federation
#   2. target_shape - target shape interface unified across the Federation


settings:
  listen_host: localhost  # listen FQDN or ip
  listen_port: 50050  # listen port
  sample_shape: [""]  # will not be used
  target_shape: [""]  # will not be used
  envoy_health_check_period: 60  # in seconds
  install_requirements: false
  review_experiment: false
